on:
  push:
    tags:
      - adelie-easy/*
jobs:
  build-adelie-easy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: ./adelie.sh
        env:
          PACKAGES_REMOTE: https://github.com/wh0/adelie-packages.git
          # https://git.adelielinux.org/adelie/packages/-/tree/current/system/easy-kernel
          PACKAGES_COMMIT: 8d373cee60231d35782f34c4a9777d7fde352bf5
          # https://hub.docker.com/r/adelielinux/adelie
          ADELIE_TAG: 1.0-beta6
          ADELIE_MIRROR: https://plug-mirror.rcac.purdue.edu/adelie
          # https://hub.docker.com/_/debian
          DEBIAN_TAG: unstable-20251020
      - uses: actions/upload-artifact@v4
        with:
          name: adelie-easy
          path: |
            adelie-packages/system/easy-kernel/src/*.deb
            adelie-packages/system/easy-kernel/src/linux-upstream_*.*
  attest-adelie-easy:
    runs-on: ubuntu-24.04
    needs: build-adelie-easy
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: adelie-easy
          pattern: linux-upstream_*.changes
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: linux-upstream_*.changes
  release-adelie-easy:
    runs-on: ubuntu-24.04
    needs: attest-adelie-easy
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: adelie-easy
      - run: gh -R ${{ github.repository }} release create ${{ github.ref_name }} *.deb linux-upstream_*.*
        env:
          GITHUB_TOKEN: ${{ github.token }}
