on:
  push:
    tags:
      - gentoo-gentoo/*
jobs:
  build-gentoo-gentoo:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - run: ./gentoo.sh
        env:
          # https://hub.docker.com/r/gentoo/stage3
          GENTOO_TAG: 20251015
          # https://packages.gentoo.org/packages/sys-kernel/gentoo-kernel
          GENTOO_VERSION: 6.12.47
          # https://hub.docker.com/_/debian
          DEBIAN_TAG: unstable-20251020⁠
      - run: |
          sudo chmod 755 portage/sys-kernel/gentoo-kernel-*
          sudo chmod 755 portage/sys-kernel/gentoo-kernel-*/work
      - uses: actions/upload-artifact@v4
        with:
          name: gentoo-gentoo
          path: |
            portage/sys-kernel/gentoo-kernel-*/work/*.deb
            portage/sys-kernel/gentoo-kernel-*/work/linux-upstream_*.*
  attest-gentoo-gentoo:
    runs-on: ubuntu-24.04
    needs: build-gentoo-gentoo
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: gentoo-gentoo
          pattern: gentoo-kernel-*/work/linux-upstream_*.changes
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: gentoo-kernel-*/work/linux-upstream_*.changes
  release-gentoo-gentoo:
    runs-on: ubuntu-24.04
    needs: attest-gentoo-gentoo
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: gentoo-gentoo
      - run: gh -R ${{ github.repository }} release create ${{ github.ref_name }} gentoo-kernel-*/work/*.deb gentoo-kernel-*/work/linux-upstream_*.*
        env:
          GITHUB_TOKEN: ${{ github.token }}
